//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace LON.Admin {
    
    
    public partial class adminDefault {
        
        /// <summary>
        /// defaultAdminMainCategoryManagement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LONCustomControl.LonCustCon defaultAdminMainCategoryManagement;
        
        /// <summary>
        /// defaultAdminParentCategoryManagement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LONCustomControl.LonCustCon defaultAdminParentCategoryManagement;
        
        /// <summary>
        /// defaultAdminProductManagement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LONCustomControl.LonCustCon defaultAdminProductManagement;
        
        /// <summary>
        /// defaultAdminPopUp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LONCustomControl.LonCustCon defaultAdminPopUp;
    }
}
